@startuml diagrama_clases

package Strayegy_Pattern{

    interface UserPermissions {
        + canManageDevices() : boolean
        + canManageProjects() : boolean
    }

    class MemberPermissions implements UserPermissions {
        + canManageDevices() : boolean
        + canManageProjects() : boolean
    }
    class OwnerPermissions implements UserPermissions {
        + canManageDevices() : boolean
        + canManageProjects() : boolean
    }
}

package Singleton_Pattern{

    class SystemConfig {
        - instance : SystemConfig {static}
        - defaultDailyLimit : double
        - defaultMonthlyLimit : double
        - defaultLanguage: String
        - SystemConfig()
        + getInstance() : SystemConfig {static}
        + getDefaultDailyLimit() : double
        + getDefaultMonthlyLimit() : double
        + getDefaultLanguage(): String
    }
}

package enums{
    enum DeviceStatus{
        ONLINE
        OFFLINE
    }

    enum RiskConsumption {
            LOW
            MEDIUM
            HIGH
            CRITICAL
    }

    enum AlertType{
        THRESHOLD
        CONNECTIVITY
    }

    enum AlertSeverity{
        WARNING
        CRITICAL
    }

    enum AlertStatus{
        PENDING
        RESOLVED
    }

    enum NotificationsStatus{
        READ
        UNREAD
    }

    enum Role{
        OWNER
        MEMBER
    }
}

package Domain_User-Configuration{
    abstract class User {
        - idUser : String
        - name : String
        - email : String
        - cellphone : String
        - password : String
        - emailVerified : boolean
        - profileImage : String
        - dateOfRegistration : Date
        - permissions : UserPermissions
        + register() : void
        + login() : void
        + logout() : void
        + updateInfo():void
        + deleteAccount() : void
        + canManageDevices() : boolean
    }

    class OwnerUser extends User {
        + linkDevice(d : Device, project : Project) : void
        + removeDevice(d : Device, project : Project) : void
        + addUserToProject(u : User, project : Project) : void
        + removeUserFromProject(u: User, p: Project): void
        + getAllDevices(project : Project) : List<Device>
    }

    class MemberUser extends User {
        + toggleFavorite(project : Project) : void
        + leaveProject(project : Project) : void
    }

    class UserConfiguration {
        - notifyByEmail : boolean
        - notifyByPush : boolean
        - colorTheme: String
        - language: String
        - socialProvider: String
        + configureNotifications() : void
        + changeColorTheme(): void
        + changeLanguage():void
        + resetPassword():void
    }
}

package Domain_Devices-Measurements{

    class ProjectType {
        - idProjectType : String
        - name : String
    }

    class ProjectThresholds {
        - idThreshold : String
        - dailyLimit : double
        - monthlyLimit : double
        - useSystemDefaults : boolean
        + resetToDefaults() : void
    }

    class Project{
        - projectCode: String
        - name: String
        - otherProjectType: String
        - address: String
        - accessCode: String
        - description: String
        - creationDate: Date
        - projectType: ProjectType
        - thresholds: ProjectThresholds
        + addDevice(d: Device): void
        + updateThresholds(daily: double, monthly: double): void
    }

    class ApplianceType {
        - idApplianceType : String
        - name : String
    }

    class Device {
        - idDevice : String
        - name : String
        - applianceType : ApplianceType
        - location : String
        - description : String
        - status : DeviceStatus
        - signalStrength : int
        - installationDate : Date
        - lastReadingAt: LocalDateTime
        - deviceCode : String
        - apiKey : String
        - observers : List<MeasurementObserver>
        + takeMeasurement() : Measurement
        + getUsageHistory() : UsageHistory
        + updateStatus() : void
        + subscribe(o : MeasurementObserver) : void
        + unsubscribe(o : MeasurementObserver) : void
        + notify(m : Measurement) : void
    }

    class Measurement {
        - idMeasurement : String
        - datetime : LocalDateTime
        - voltage : double
        - current : double
        - activePower : double
        - storedEnergy : double
        + getVoltage() : double
        + getCurrent() : double
        + getActivePower() : double
        + getStoredEnergy() : double
    }

    class UsageHistory {
        - idUsageHistory : String
        - period : String
        - startDate : Date
        - endDate : Date
        - totalConsumption : double
        - averageConsumption : double
        + getSummary() : String
        + getMeasurements() : List<Measurement>
    }
}

package Observer_Pattern{
    interface MeasurementObserver {
        + onMeasurement(m : Measurement) : void
    }

    class AlertObserver implements MeasurementObserver {
        + onMeasurement(m : Measurement) : void
    }

    class RecommendationObserver implements MeasurementObserver {
        + onMeasurement(m : Measurement) : void
    }
}

package Domain_Notifications{
    abstract class Notification {
        - idNotification : String
        - messageKey : String
        - project : Project
        - device : Device
        - datetime : LocalDateTime
        + generate() : void
        + send() : void
    }
    class ConsumptionLevel{
        - idConsumptionLevel: String
        - name: RiskConsumption
        - description: String
        - minLimit: double
        - maxLimit: double
    }
    class Alert extends Notification {
        - type : AlertType
        - severity : AlertSeverity
        - status : AlertStatus
        - consumptionLevel : ConsumptionLevel
        - measurement : Measurement
        + resolveAlert() : void
    }

    class Recommendation extends Notification {
        - status : NotificationsStatus
        + markAsRead() : void
        + applyRecomendation(): void
    }
}

package Factory_Methon_Pattern{
    abstract class NotificationFactory {
        + createFromMeasurement(m : Measurement, risk : RiskConsumption) : Notification
        + createFromDeviceStatus(project : Project, device : Device) : Notification
    }

    class AlertFactory extends NotificationFactory {
        + createFromMeasurement(m : Measurement, risk : RiskConsumption) : Alert
        + createFromDeviceStatus(project : Project, device : Device) : Alert
    }

    class RecommendationFactory extends NotificationFactory {
        + createFromMeasurement(m : Measurement, risk : RiskConsumption) : Recommendation
        + createFromDeviceStatus(project : Project, device : Device) : Recommendation
    }

}

' Relationships


' Strategy
User ..> UserPermissions : use

' Singleton
UserConfiguration ..> SystemConfig
User ..> SystemConfig : use
ProjectThresholds ..> SystemConfig : use defaults

' Compocition user
User "1" *-- "1" UserConfiguration

' Composition project
Project "1" *-- "1" ProjectThresholds
Project "1" o-- "0..*" Device
Project "*" o-- "1" ProjectType : uses
Project "1" o-- "0..*" Alert
Project "1" o-- "0..*" Recommendation

' Composition device
Device "1" *-- "0..*" Measurement
Device "1" *-- "0..1" UsageHistory
Device "*" o-- "1" ApplianceType : uses
Device "1" o-- "0..*" Alert
Device "1" o-- "0..*" Recommendation

' Device uses DeviceStatus
Device ..> DeviceStatus: use

' Observer
Device ..> MeasurementObserver : notify

' Factory Method
AlertFactory ..> Alert : create
RecommendationFactory ..> Recommendation : create
Alert ..> RiskConsumption
Alert ..> AlertType
Alert ..> AlertSeverity
Alert ..> AlertStatus
Recommendation ..> NotificationsStatus


@enduml